"""empty message

Revision ID: 0e2b7c7b651d
Revises: f5b45c83c0cd
Create Date: 2022-06-28 14:26:51.277645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2b7c7b651d'
down_revision = 'f5b45c83c0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_message_board', sa.Column('publisher_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_message_board', 'publisher_id')
    # ### end Alembic commands ###
