"""empty message

Revision ID: 1b1057c781cc
Revises: 605367f671ee
Create Date: 2022-06-27 15:32:33.654843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b1057c781cc'
down_revision = '605367f671ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_dictionaries', 'code1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_dictionaries', sa.Column('code1', mysql.VARCHAR(length=4), nullable=True))
    # ### end Alembic commands ###
