"""empty message

Revision ID: 42016723d7f4
Revises: c299896ac9d6
Create Date: 2022-06-27 10:20:13.040175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42016723d7f4'
down_revision = 'c299896ac9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_user', sa.Column('user_type', sa.Integer(), nullable=True))
    op.drop_column('db_user', 'identity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_user', sa.Column('identity', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('db_user', 'user_type')
    # ### end Alembic commands ###
