"""empty message

Revision ID: 59c7e4dd0f0d
Revises: 0e2b7c7b651d
Create Date: 2022-06-28 15:03:25.860902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59c7e4dd0f0d'
down_revision = '0e2b7c7b651d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_message_board', 'publisher_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_message_board', sa.Column('publisher_id', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
