"""empty message

Revision ID: 605367f671ee
Revises: 1a6ce2a1cfd9
Create Date: 2022-06-27 15:32:11.482799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605367f671ee'
down_revision = '1a6ce2a1cfd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_dictionaries', sa.Column('code1', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_dictionaries', 'code1')
    # ### end Alembic commands ###
