"""empty message

Revision ID: 707a5728cc06
Revises: 1b1057c781cc
Create Date: 2022-06-28 12:19:24.363060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707a5728cc06'
down_revision = '1b1057c781cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_message_board',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['db_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['db_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_message_board')
    # ### end Alembic commands ###
