"""empty message

Revision ID: c299896ac9d6
Revises: 79913118f34d
Create Date: 2022-06-27 10:19:08.499620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c299896ac9d6'
down_revision = '79913118f34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_user', sa.Column('identity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_user', 'identity')
    # ### end Alembic commands ###
