"""empty message

Revision ID: f5b45c83c0cd
Revises: 707a5728cc06
Create Date: 2022-06-28 12:47:45.930510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b45c83c0cd'
down_revision = '707a5728cc06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('db_message_board_ibfk_1', 'db_message_board', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('db_message_board_ibfk_1', 'db_message_board', 'db_user', ['parent_id'], ['id'])
    # ### end Alembic commands ###
